name: build
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker run -v .:/src -w /src vvakame/review:5.8 make all
      - uses: actions/upload-artifact@v3
        with:
          name: book
          path: c81.pdf
